variables:
  DOCKER_REPO:           {{.DockerConfig.RegistryUrl}}
  PROJECT_BUILDER:       {{.DockerConfig.Image}}
  DEPLOYER:              {{.GitLabCIConfig.Deployer}}
  K8S_DEV_NAMESPACE:     {{.GitLabCIConfig.K8SDevNamespace}}
  K8S_PROD_NAMESPACE:    {{.GitLabCIConfig.K8SProdNamespace}}
  K8S_EKS_DEV_CLUSTER:   {{.GitLabCIConfig.K8SDevCluster}}
  K8S_EKS_PROD_CLUSTER:  {{.GitLabCIConfig.K8SProdCluster}}
  STG_DIRECTORY:         kubernetes-stg
  PROD_DIRECTORY:        kubernetes-prod

{{ if eq .BuildTool "gradle-project"}}
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
{{end}}

stages:
  - prepare
  - build
  - check
  {{if eq .EnableSonar true}}- sonar{{end}}
  - pack
  - deploy

# Build project
build:
  image: $PROJECT_BUILDER
  stage: build
  script:{{ if eq .BuildTool "gradle-project"}}
    - ./gradlew clean build -x test --build-cache --parallel{{end}}
  artifacts:
    paths: [build/libs, build/reports, build/classes]
  tags:{{ range $index, $element := .GitLabCIConfig.Tags}}
    - {{$element}}{{end}}
  except:{{ range $index, $element := .GitLabCIConfig.Excepts}}
    - {{$element}}{{end}}

# Execute code style check & Tests
checkstyle: {{ if eq .BuildTool "gradle-project"}}
  image: $PROJECT_BUILDER
  stage: check
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull
  script:
    - ./gradlew check --build-cache --parallel
  artifacts:
  tags:{{ range $index, $element := .GitLabCIConfig.Tags}}
    - {{$element}}{{end}}
  except:{{ range $index, $element := .GitLabCIConfig.Excepts}}
    - {{$element}}{{end}}
  {{end}}

# Execute code style check & Tests
test:
  image: $PROJECT_BUILDER
  stage: check
  {{ if eq .BuildTool "gradle-project"}}
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull
  script:
    - ./gradlew check --build-cache --parallel
  {{end}}
  artifacts:
  tags:{{ range $index, $element := .GitLabCIConfig.Tags}}
  - {{$element}}{{end}}
  except:{{ range $index, $element := .GitLabCIConfig.Excepts}}
  - {{$element}}{{end}}

{{if eq .EnableSonar true}}
# Execute Sonar check
SonarQube Check:
  image: {{.GitLabCIConfig.SonarQubeScannerImage}}
  stage: sonar
  cache:
    policy: pull
  script:
    - sonar-scanner -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_SLUG} -Dsonar.gitlab.project_id=${CI_PROJECT_ID} -Dsonar.projectVersion=${CI_COMMIT_REF_SLUG}
  tags:{{ range $index, $element := .GitLabCIConfig.Tags}}
  - {{$element}}{{end}}
  except:{{ range $index, $element := .GitLabCIConfig.Excepts}}
  - {{$element}}{{end}}
  only:
    - tags
  allow_failure: true
{{end}}

# Create Docker image based on release tag
pack:
  stage: pack
  cache: {}
  variables:
    IMAGE_NAME:     $DOCKER_REPO/{{.Name}}:$CI_COMMIT_TAG
  script:
    - docker build -t $IMAGE_NAME .
    - docker push     $IMAGE_NAME
    - docker rmi      $IMAGE_NAME
  tags:{{ range $index, $element := .GitLabCIConfig.Tags}}
  - {{$element}}{{end}}
  only:
    - tags

# Create K8s Yml configuration files for latest stable release
prepare-before-release:
  image: {{.DockerConfig.BashImage}}
  stage: prepare
  cache: {}
  variables:
    IMAGE_NAME:     $DOCKER_REPO/{{.Name}}:$CI_COMMIT_TAG
  before_script:
    - export VERSION=$(echo ${CI_COMMIT_REF_SLUG} | cut -d'-' -f 1-3)
  script:
    - mkdir $PROD_DIRECTORY
    - mkdir $STG_DIRECTORY
    - cat kubernetes/prod/kube-config.yml                      | build_pipeline/mo.sh > $PROD_DIRECTORY/deployment.yml
    - cat kubernetes/stg/kube-config.yml                       | build_pipeline/mo.sh > $STG_DIRECTORY/kube-config.yml
  artifacts:
    paths: [$PROD_DIRECTORY, $STG_DIRECTORY]
    expire_in: 7 days
  tags:{{ range $index, $element := .GitLabCIConfig.Tags}}
  - {{$element}}{{end}}
  only:
    - master
    - tags

deploy-version:
  image: $DEPLOYER
  stage: deploy
  script:
    - kubectl --context $K8S_EKS_DEV_CLUSTER --namespace=$K8S_DEV_NAMESPACE  apply -f $STG_DIRECTORY
  tags:{{ range $index, $element := .GitLabCIConfig.K8SDeployStagingEnvTags}}
  - {{$element}}{{end}}
  only:
    - tags

deploy-manual:
  image: $DEPLOYER
  stage: deploy
  script:
    - kubectl --context $K8S_EKS_PROD_CLUSTER apply -f $PROD_DIRECTORY
  tags:{{ range $index, $element := .GitLabCIConfig.K8SDeployProdEnvTags}}
  - {{$element}}{{end}}
  when: manual
  only:
    - tags
